package com.marticus.EmployeeManagement.Entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Table(name="employees")
public class Employee  {
	
	@Id
	@GeneratedValue(strategy= GenerationType.IDENTITY)
	@Column(name="id",nullable=false)
	long id;// serialized id auto generated by mysql
	
	@Column(name="Emp_Id")
	String employeeId; //to store employee Id
	
	@Column(name="Emp_Name")
	String employeeName;//to store employee name
	
	@Column(name="Salary")
	int salary;//to store the employee's salary
	
	@Column(name="Age")
	int age;//to store age of the employee
	
	@Column(name="Aadhar")
	long aadhar;//to employee aadhar no
	
	@Column(name="Department")
	String department;//to store the department which the employee belongs to
	
}